# Generated by Django 5.1.7 on 2025-03-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartiCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('era', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('track_length', models.CharField(blank=True, max_length=100, null=True)),
                ('leak_date', models.CharField(blank=True, max_length=100, null=True)),
                ('file_date', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('available_length', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('primary_link', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'db_table': 'carti_catalog',
                'ordering': ['era', 'name'],
                'managed': False,
            },
        ),
    ]
