# Generated by Django 5.1.7 on 2025-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetTab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sheet_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sheet Tab',
                'verbose_name_plural': 'Sheet Tabs',
                'db_table': 'sheet_tab',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
