# Generated by Django 5.1.7 on 2025-03-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_songmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_songs', to='catalog.sheettab')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.carticatalog')),
            ],
            options={
                'verbose_name': 'Song Category',
                'verbose_name_plural': 'Song Categories',
                'db_table': 'song_category',
                'managed': True,
                'unique_together': {('song', 'sheet_tab')},
            },
        ),
    ]
