# Generated by Django 5.1.7 on 2025-03-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_songcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('era', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('was_used', models.BooleanField(default=False)),
                ('links', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Art Media',
                'verbose_name_plural': 'Art Media',
                'db_table': 'art_media',
                'ordering': ['era', 'name'],
                'managed': True,
            },
        ),
    ]
