# Generated by Django 5.1.7 on 2025-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_artmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('outlet', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('interview_type', models.CharField(blank=True, max_length=100, null=True)),
                ('available', models.BooleanField(default=True)),
                ('archived_link', models.URLField(blank=True, null=True)),
                ('source_links', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'interview',
                'ordering': ['era', 'date'],
                'managed': True,
            },
        ),
    ]
