# Generated by Django 5.1.7 on 2025-03-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(blank=True, max_length=100, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photographer', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('pic_type', models.CharField(blank=True, max_length=100, null=True)),
                ('portion', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('source_links', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fit Pic',
                'verbose_name_plural': 'Fit Pics',
                'db_table': 'fit_pic',
                'ordering': ['era', 'release_date'],
                'managed': True,
            },
        ),
    ]
