# Generated by Django 5.1.7 on 2025-03-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_fitpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('last_post', models.CharField(blank=True, max_length=100, null=True)),
                ('still_used', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Account',
                'verbose_name_plural': 'Social Media Accounts',
                'db_table': 'social_media',
                'ordering': ['era', 'platform'],
                'managed': True,
            },
        ),
    ]
