# Generated by Django 5.1.7 on 2025-03-15 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitpic',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Fit Pic', 'verbose_name_plural': 'Fit Pics'},
        ),
        migrations.CreateModel(
            name='SongVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the voter for preventing duplicate votes')),
                ('session_key', models.CharField(blank=True, help_text='Session key to track votes', max_length=40, null=True)),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='catalog.carticatalog')),
            ],
            options={
                'verbose_name': 'Song Vote',
                'verbose_name_plural': 'Song Votes',
                'db_table': 'song_vote',
                'managed': True,
                'unique_together': {('song', 'ip_address')},
            },
        ),
    ]
