# Generated by Django 5.1.7 on 2025-03-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_fitpic_options_songvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_custom_homepage', models.BooleanField(default=False, help_text='When enabled, the homepage will use the songs selected below instead of the Recent tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homepage_songs', models.ManyToManyField(blank=True, help_text='Select songs to display on the homepage (max 10 will be used)', related_name='homepage_displays', to='catalog.carticatalog')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
                'db_table': 'homepage_settings',
                'managed': True,
            },
        ),
    ]
