# Generated by Django 5.1.7 on 2025-03-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_homepagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='enable_custom_recently_leaked',
            field=models.BooleanField(default=False, help_text='When enabled, the Recently Leaked section will use the songs selected below instead of the most recent leaks'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='recently_leaked_songs',
            field=models.ManyToManyField(blank=True, help_text='Select songs to display in the Recently Leaked section (max 5 will be used)', related_name='recently_leaked_displays', to='catalog.carticatalog'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='homepage_songs',
            field=models.ManyToManyField(blank=True, help_text='Select songs to display in the main Recent Songs section (max 10 will be used)', related_name='homepage_displays', to='catalog.carticatalog'),
        ),
    ]
