# Generated by Django 5.1.7 on 2025-03-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_homepagesettings_enable_custom_recently_leaked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_hash', models.CharField(db_index=True, help_text='Hashed identifier for the client', max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('last_vote_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client Identifier',
                'verbose_name_plural': 'Client Identifiers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='songvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='songvote',
            name='client_identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Hashed client identifier', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='songvote',
            unique_together={('song', 'client_identifier')},
        ),
    ]
