# Generated by Django 5.1.7 on 2025-03-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_clientidentifier_alter_songvote_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_identifier', models.CharField(db_index=True, help_text='Client hash identifier to track user bookmarks', max_length=64)),
                ('collection_name', models.CharField(default='My Collection', help_text='Custom collection name for organizing bookmarks', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='catalog.carticatalog')),
            ],
            options={
                'verbose_name': 'Song Bookmark',
                'verbose_name_plural': 'Song Bookmarks',
                'db_table': 'song_bookmark',
                'managed': True,
                'unique_together': {('client_identifier', 'song', 'collection_name')},
            },
        ),
    ]
