# Generated by Django 5.1.7 on 2025-03-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_songbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInsights',
            fields=[
            ],
            options={
                'verbose_name': 'Recommendation Insights',
                'verbose_name_plural': 'Recommendation Insights',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.songvote',),
        ),
    ]
