from django.core.management.base import BaseCommand
from catalog.models import CartiCatalog, SheetTab, SongMetadata

class Command(BaseCommand):
    help = 'Imports additional stems data from Google Sheets'

    def handle(self, *args, **options):
        # Get the Stems tab
        stems_tab = SheetTab.objects.filter(name='Stems').first()
        if not stems_tab:
            self.stderr.write(self.style.ERROR('Stems tab not found!'))
            return
            
        self.stdout.write(f'Using Stems tab with ID {stems_tab.id}')
        
        # Define the additional stems data
        stems_data = [
            {
                'era': 'Ca$h Carti Season',
                'name': 'Finesse Remix [Instrumental] (prod. captain crunch & Chinatown)',
                'notes': 'OG Filename: aston martin (cc x chinatown)\nInstrumental for "Finesse Remix"',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/42ecb989e3b19ebc87a03d4f98a15bf3',
            },
            {
                'era': 'Ca$h Carti Season',
                'name': 'Turn Up (prod. Don Cannon & Maaly Raw)',
                'notes': 'Instrumental for Turn Up',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://soundcloud.com/djdoncannon/unreleased-beat-2016-cannon-maaly-raw',
            },
            {
                'era': 'Ca$h Carti Season',
                'name': 'What [Instrumental]',
                'notes': 'OG Filename: MEDITATE 99\nFilename shows the beat was named "Meditate".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/8b94bbad271a85122fdc0e18d3dc222c',
            },
            {
                'era': 'Ca$h Carti Season',
                'name': 'LAMB$ - 2 Door [Protools] (feat. Playboi Carti)',
                'notes': 'Snippet leaked by Handler.',
                'leak_date': '',
                'type': 'Session',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/09a9930c73a5d156e0ef33bd67643a1a',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Foreign South America [Instrumental] (prod. Chinatown)',
                'notes': 'Instrumental for Foreign South America',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/bbfc2c7c54690411efa2a10a400a95f8',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Autograph [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'Instrumental for Autograph',
                'leak_date': 'Sep 21, 2024',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/d0eab4ee2806c575cb8c65fff5a57ff3',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Brand New [Instrumental] (prod. Chinatown)',
                'notes': 'Instrumental to the unreleased song "Brand New".',
                'leak_date': '2022',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/19fd8c8fb870f0d0ddd586b0dc4aee85',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Countin\' Caskets [Instrumental] (prod. MilanMakesBeats)',
                'notes': 'Instrumental to the unreleased song "Countin\' Caskets". Filename shows the beat was named "Havin".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/68493881afebd076671a9227b3b9a6c3',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Full Metal [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'OG Filename: check5 130\nInstrumental for the unreleased song "Full Metal".',
                'leak_date': '2024',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://www.youtube.com/watch?v=jWHP8-9d_3c&ab_channel=ExtraSossy',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Half & Half [Session] (prod. Southside)',
                'notes': 'Snippet was previewed on November 1, 2022.',
                'leak_date': 'Nov 1, 2022',
                'type': 'Session',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/53b3541cdbb5e094ab9298e99938c877',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Kelly K [Stems]',
                'notes': 'Stems for the released song "Kelly K".',
                'leak_date': 'Feb 3, 2025',
                'type': 'Studio Stems',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://krakenfiles.com/view/hIXCUaNA2g/file.html',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Kelly K [Sample Loop]',
                'notes': 'Original loop used in "Kelly K".',
                'leak_date': '',
                'type': 'Sample',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/50d58476fd6d4186416cdedcc879ef2f',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Magnolia [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'Instrumental for Magnolia.',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/38449896cf113a585e41e1a340cb6602',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Snitches [Instrumental] (prod. Southside)',
                'notes': 'Previewed on Southside\'s livestream on December 2016.',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://music.froste.lol/video/89df417b123a9286b80317a37acb5571/play',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Magnolia [Stems] (prod. Pi\'erre Bourne)',
                'notes': 'Leaked on October 20, 2022.',
                'leak_date': 'Oct 20, 2022',
                'type': 'Studio Stems',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pixeldrain.com/u/czdq6TUq',
            },
            {
                'era': 'Playboi Carti',
                'name': 'No Charm [Instrumental] (prod. Harry Fraud)',
                'notes': 'Instrumental to the unreleased song "No Charm".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/ab042c5054c9b192407bcee5adb37dd9',
            },
            {
                'era': 'Playboi Carti',
                'name': 'One Day [Session] (prod. Pi\'erre Bourne)',
                'notes': 'Session for One Day. Leaked by KAPPER for free.',
                'leak_date': 'Feb 19, 2024',
                'type': 'Session',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://krakenfiles.com/view/JhhU5oRyrm/file.html',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Other Shit [Session] (feat. Lil Uzi Vert) (prod. Hit-Boy)',
                'notes': 'Leaked on April 4, 2022. Includes Carti & Uzi vocal takes as well as instrumental stems. Has a few unused lines from Uzi.',
                'leak_date': 'Apr 4, 2022',
                'type': 'Session',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://drive.google.com/file/d/1Pl-8fWcvK9gwJdJ4lsyuQYcaOrzfhda0/view?usp=sharing',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Places [Instrumental] [V1] (prod. Harry Fraud)',
                'notes': 'Instrumental to the unreleased song "Places".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://music.froste.lol/song/bbf086b14abc53170a6c630a4d327541/play',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Places [Instrumental] [V2] (prod. Harry Fraud)',
                'notes': 'Alternate instrumental to the unreleased song "Places".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/4aff8186ac32620aa22ca07202f639fc',
            },
            {
                'era': 'Playboi Carti',
                'name': 'Red Bandana Santana [Instrumental] (prod. Polo Boy Shawty)',
                'notes': 'Original type beat that Carti would use for his track "Red Bandana Santana". Video shows the beat was titled "23 Vlone". Has "purchase your tracks today" tag throughout the song.',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://www.youtube.com/watch?v=YBJhmvQqQ-E&list=PLxwk2ZgJMXasKHyKspIzi6S_v_K6wlmxx&index=38',
            },
            {
                'era': 'Playboi Carti',
                'name': 'They Hatin\' [Sample Loop] (prod. DJ Dahi)',
                'notes': 'Original loop used in the unreleased song "They Hatin\'.',
                'leak_date': '',
                'type': 'Other',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/a9b89c3e359371c72548ddcf2e745bfe',
            },
            {
                'era': 'Playboi Carti',
                'name': 'We So Proud Of Him (Instrumental) (prod. 6Silky & BasedTJ)',
                'notes': 'The beat Carti used for "We So Proud Of Him" is a Playboi Carti type beat posted to youtube in 2016.',
                'leak_date': 'Feb 21, 2016',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://www.youtube.com/watch?v=8BO5mY0LnHE&ab_channel=6Silky',
            },
            {
                'era': 'Playboi Carti',
                'name': 'A$AP Ferg - Mad Man [Instrumental] (feat. Playboi Carti) (prod. Honorable C.N.O.T.E.)',
                'notes': 'Samples "Tear Da Club Up" by Three 6 Mafia',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/b834a8dc3cdeef68be778d481681dffc',
            },
            {
                'era': '16*29',
                'name': 'Big Bank [Acapella] (w/ Lil Uzi Vert) (prod. Pi\'erre Bourne)',
                'notes': 'Previewed by Trillo Bourne on Instagram live.',
                'leak_date': '',
                'type': 'Acapella',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://music.froste.lol/video/16ea3430441752827c4413d418eb0745/play',
            },
            {
                'era': '16*29',
                'name': 'Swag Disease [Instrumental] (w/ Lil Uzi Vert) (prod. DP Beats)',
                'notes': 'Instrumental to the leaked song "Swag Disease". Slightly different from the instrumental on the leaked',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/ba4e70bb62e47819df16cfcddf6bae6a',
            },
            {
                'era': 'Die Lit',
                'name': 'No Time [Instrumental] (feat. Gunna) (prod. Pi\'erre Bourne)',
                'notes': 'Instrumental for "No Time".',
                'leak_date': 'Nov 29, 2019',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/0d511f937e89d2099e605cc970953c5e',
            },
            {
                'era': 'Die Lit',
                'name': 'Goyard Shopping Bag [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'OG Filename: 01 peirre beat 157 bpm 2\nVersion of the "Watch" beat used for "Goyard Shopping Bag".',
                'leak_date': 'Jan 29, 2023',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://krakenfiles.com/view/tzuprSjwgq/file.html',
            },
            {
                'era': 'Die Lit',
                'name': 'Highschool [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'Instrumental for Highschool',
                'leak_date': 'Aug 13, 2024',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://krakenfiles.com/view/eyb93KAzFa/file.html',
            },
            {
                'era': 'Die Lit',
                'name': 'Lit [Sample Loop] (prod. CuBeatz)',
                'notes': 'The original melody used to create "Lit".',
                'leak_date': 'Jul 12, 2022',
                'type': 'Other',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/2da1b2daaa157df1baf0e886cae1aabb',
            },
            {
                'era': 'Die Lit',
                'name': 'Shawty In Love [Sample Loop]',
                'notes': 'The original melody used to create "Shawty In Love".',
                'leak_date': '',
                'type': 'Other',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/6145cfe049c2fea12174b9702d43de8d',
            },
            {
                'era': 'Die Lit',
                'name': 'Toke [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'Earlier version of the "Toke" beat previewed by Carti.',
                'leak_date': 'Sep 2, 2017',
                'type': 'Instrumental',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://music.froste.lol/video/06948cef815359b5a2910c824bc71a30/play',
            },
            {
                'era': 'Die Lit',
                'name': 'Trap (prod. Pi\'erre Bourne) (Classroom)',
                'notes': 'Session for Trap. Leaked by KAPPER for free.',
                'leak_date': 'Feb 19, 2024',
                'type': 'Session',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/5e1e4e47f69826ac73e9a2285681df0b',
            },
            {
                'era': 'Die Lit',
                'name': 'Vlone Jacket [Instrumental] (prod. Pi\'erre Bourne)',
                'notes': 'OG Filename: meggriff4 157\nAn alternate instrumental for "Vlone Jacket".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/e858bbaf41ce25c67bf888f09b40c4ff',
            },
            {
                'era': 'Die Lit',
                'name': 'R.I.P [Sample] (prod. Pi\'erre Bourne)',
                'notes': 'Samples "What About Us" by Jodeci.',
                'leak_date': '',
                'type': 'Sample',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://youtu.be/tJeR3JJBxUg?si=N7P1CqHsLGWe9--A',
            },
            {
                'era': 'Die Lit',
                'name': 'Shoota [Session] (feat. Lil Uzi Vert) (prod. Maaly Raw)',
                'notes': 'Unleaked session for "Shoota". Snippets leaked in January 2024.',
                'leak_date': 'Jan 17, 2024',
                'type': 'Session',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/17969ea940401f739e869af9b1110cdf',
            },
            {
                'era': 'Die Lit',
                'name': 'Shoota [Instrumental] (prod. Maaly Raw)',
                'notes': 'Unleaked instrumental to "Shoota" from the session.',
                'leak_date': 'Jan 17, 2024',
                'type': 'Instrumental',
                'available_length': 'Snippet',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/f300710814a3db287068028293ad993f',
            },
            {
                'era': 'Die Lit',
                'name': 'A$AP Ferg - Mad Man [Acapella] (feat. Playboi Carti)',
                'notes': 'Acapella for the released song "Mad Man"',
                'leak_date': '',
                'type': 'Acapella',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://krakenfiles.com/view/8bTqO23xzg/file.html',
            },
            {
                'era': 'Die Lit',
                'name': 'A$AP Ferg - Mad Man [Instrumental] (feat. Playboi Carti) (prod. Honorable C.N.O.T.E.)',
                'notes': 'Instrumental to the released song "Mad Man".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/8d2558efadb55e5218b39c647cffd3b5',
            },
            {
                'era': 'Die Lit',
                'name': 'Benjamin Kickz - Choppa [V2] [Session] (feat. Playboi Carti) (prod. Pi\'erre Bourne)',
                'notes': 'Session for the second version of the unreleased Benjamin Kickz song "Choppa".',
                'leak_date': '',
                'type': 'Studio Stems',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/ab92204dcf56c3aece1f614416d4b19b',
            },
            {
                'era': 'Die Lit',
                'name': 'MilanMakesBeats - Butterfly Coupe [Instrumental] (feat. Playboi Carti & Yung Bans) (prod. MilanMakesBeats)',
                'notes': 'Instrumental to the released song "Butterfly Coupe".',
                'leak_date': '',
                'type': 'Instrumental',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/2e156cf1d54e652566eef28d70438def',
            },
            {
                'era': 'Die Lit',
                'name': 'NAV - Minute [V1] [Vocal Stems] (feat. Playboi Carti & Offset) (prod. Pi\'erre Bourne)',
                'notes': 'Vocal stems for Carti\'s original verse on "Minute" that were used in fake edits.',
                'leak_date': '',
                'type': 'Session',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://pillowcase.su/f/3e20992c97ea7f9e44ed9f25d54a2771\nhttps://pillowcase.su/f/225cd0c3321976fab64cdb771d248fb5',
            },
            {
                'era': 'Die Lit',
                'name': 'Pi\'erre Bourne - Yo Pi\'erre [Stems] (feat. Playboi Carti) (prod. Pi\'erre Bourne)',
                'notes': 'Leaked on June 24, 2022.',
                'leak_date': 'Jun 24, 2022',
                'type': 'Two Track',
                'available_length': 'Full',
                'quality': 'High Quality',
                'links': 'https://plwcse.top/f/92120ce9b3b35ab832ee892dcfa2d26d\nhttps://plwcse.top/f/2e90d577341fd8635edcc49b72e8cf6c',
            },
        ]
        
        # Create records for each item
        created_count = 0
        for data in stems_data:
            # Check if song already exists to avoid duplicates
            existing = CartiCatalog.objects.filter(
                name=data['name'], 
                era=data['era']
            ).first()
            
            if existing:
                self.stdout.write(f"Song already exists: {data['name']} - Skipping.")
                continue
            
            # Create the song
            song = CartiCatalog.objects.create(
                era=data['era'],
                name=data['name'],
                notes=data['notes'],
                leak_date=data['leak_date'],
                type=data['type'],
                available_length=data['available_length'],
                quality=data['quality'],
                links=data['links'],
                primary_link=data['links'].split('\n')[0] if data['links'] else None,
            )
            
            # Create the metadata and associate with Stems tab
            SongMetadata.objects.create(
                song=song,
                sheet_tab=stems_tab,
                subsection=None,
            )
            
            created_count += 1
            
        self.stdout.write(self.style.SUCCESS(f'Added {created_count} new items to the Stems tab'))