import csv
import re
from django.core.management.base import BaseCommand
from catalog.models import Interview

class Command(BaseCommand):
    help = 'Import interviews data from provided information'

    def handle(self, *args, **options):
        # Sample data based on the provided sheet information
        interview_data = [
            # Awful Records Era
            {
                'era': 'Awful Records',
                'date': 'July 14, 2014',
                'outlet': 'Know Nothing Presents',
                'subject_matter': 'Frank Whitelemon sits down with Playboi Carti',
                'special_notes': 'First Carti Interview ever! Original video was taken down',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=Z3mjPSoQhPk',
            },
            {
                'era': 'Awful Records',
                'date': 'January 27, 2015',
                'outlet': 'HotNewHipHop',
                'subject_matter': "Meet Awful Records'Father, Archibald Slim & Playboi Carti",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=4Z8xXD90wFA',
            },
            
            # Chucky Era
            {
                'era': 'Chucky Era',
                'date': 'July 11, 2015',
                'outlet': 'RealDopeEnt',
                'subject_matter': 'Uncut Dope Season 2 Ep. 11 - Father & Playboi Carti',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=ACO5YZuTEc0&list=PLWH1685Ou0Dm3nIbtlvxbZHIVa0r9ePDk&index=15',
            },
            {
                'era': 'Chucky Era',
                'date': 'October 29, 2015',
                'outlet': 'HotNewHipHop',
                'subject_matter': 'On The Come Up: Playboi Carti',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=pFyn6Z7PQLw',
            },
            {
                'era': 'Chucky Era',
                'date': '2015',
                'outlet': 'Ian Connor',
                'subject_matter': '',
                'special_notes': 'Original video in full is lost, but a short snippet of Carti dancing to Broke Boi is the only thing that is seen of this interview, recorded by Ian Connor.',
                'interview_type': 'Interview',
                'available': False,
                'archived_link': '',
                'source_links': 'https://krakenfiles.com/view/cv5L9zTLua/file.html',
            },
            {
                'era': 'Chucky Era',
                'date': '2015',
                'outlet': 'Yung mud',
                'subject_matter': 'Playboi Carti interview + peformance',
                'special_notes': 'Original video was taken down',
                'interview_type': 'Interview + Live Performance',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=kC5DOL-P7Dc&list=PLWH1685Ou0Dm3nIbtlvxbZHIVa0r9ePDk&index',
            },
            
            # Ca$h Carti Season
            {
                'era': 'Ca$h Carti Season',
                'date': 'Early 2016',
                'outlet': '88rising',
                'subject_matter': 'A$AP Bari, Ian Connor, Playboi Carti interview',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/kSos-a1wePg?si=sQNkGE3e9aV79zng',
            },
            {
                'era': 'Ca$h Carti Season',
                'date': 'Early May 2016',
                'outlet': 'SSS Entertainment',
                'subject_matter': '',
                'special_notes': 'Was previously uploaded by the outlet on their Youtube Channel and deleted sometime later due to the interview being terrible. Features Ian Connor.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=oF49SHtXtJ0&t=338s',
            },
            {
                'era': 'Ca$h Carti Season',
                'date': '2016',
                'outlet': 'AKInATL',
                'subject_matter': 'Playboi Carti interview and BTS for Japanese media, telling the truth!',
                'special_notes': 'First and only time Carti was ever interviewed by a Japanese outlet.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=eA8HgKHgokU&list=PLWH1685Ou0Dm3nIbtlvxbZHIVa0r9ePDk&index=4',
            },
            {
                'era': 'Ca$h Carti Season',
                'date': '2016',
                'outlet': 'Lucid FC',
                'subject_matter': 'Promo for the song "What?"',
                'special_notes': '',
                'interview_type': 'Promo',
                'available': True,
                'archived_link': '',
                'source_links': 'https://vimeo.com/175795329',
            },
            {
                'era': 'Ca$h Carti Season',
                'date': '2016',
                'outlet': 'The Source',
                'subject_matter': 'Style Sector with Playboi Carti',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=oaBvNqaN3_o&list=PLWH1685Ou0Dm3nIbtlvxbZHIVa0r9ePDk&index=12',
            },
            
            # Playboi Carti (Self-Titled) Era
            {
                'era': 'Playboi Carti',
                'date': 'January 6, 2017',
                'outlet': 'Complex',
                'subject_matter': 'Playboi Carti Interview With Complex',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/iHJoS6GpeKc?si=sM000wBNmFC2t5rM',
            },
            {
                'era': 'Playboi Carti',
                'date': 'February 10, 2017',
                'outlet': 'VFILES',
                'subject_matter': 'Lil Uzi Vert and Playboi Carti | VFILES LOUD Live from Times Square',
                'special_notes': '',
                'interview_type': 'Interview + Live Performance',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=zYtJdIr1sqM&t=83s\nhttps://www.youtube.com/watch?v=VidvEmVRWXI',
            },
            {
                'era': 'Playboi Carti',
                'date': 'February 24, 2017',
                'outlet': 'The FADER',
                'subject_matter': 'Playboi Carti - Everything You Need To Know (Episode 40)',
                'special_notes': 'Playboi Carti talks about his collaboration with Frank Ocean',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/rHO6TiPLHqw?si=_hkJNL4ZVwZzxf9S',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 22, 2017',
                'outlet': 'Shark TV',
                'subject_matter': 'Playboi Carti concert recap 2017 Atlanta',
                'special_notes': 'Carti had his chain snatched during the performance at one point.',
                'interview_type': 'Live Performance',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=TGuk2qSNbXA&list=PLWH1685Ou0Dm3nIbtlvxbZHIVa0r9ePDk&index=20',
            },
            {
                'era': 'Playboi Carti',
                'date': 'March 21, 2017',
                'outlet': 'The FADER',
                'subject_matter': 'When Yachty Met Carti',
                'special_notes': "Carti and Lil Yachty talk about why Carti's tape still isn't out",
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/E5uHzO6L_EQ?si=Zm5B-IXldGhyN3tS',
            },
            {
                'era': 'Playboi Carti',
                'date': 'March 27, 2017',
                'outlet': 'XXL',
                'subject_matter': "Playboi Carti's Pitch for 2017 XXL Freshman",
                'special_notes': '',
                'interview_type': 'Promo',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/Se9mAUBU1tk?si=Pb37rIC7XDVXjgxT',
            },
            {
                'era': 'Playboi Carti',
                'date': 'April 13, 2017',
                'outlet': 'W Magazine',
                'subject_matter': 'Meet Playboi Carti, the Next Atlanta Rap Prodigy to Take Fashion By Storm',
                'special_notes': 'Carti said warily, even though he gets trolled by his fans,he likes to playfully troll his fans right back. For example, he made the cover of his highly-anticipated debut project supposedly titled Cash Carti, a collage of angry fan comments.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.wmagazine.com/story/playboi-carti-atlanta-rapper',
            },
            {
                'era': 'Playboi Carti',
                'date': 'April 20, 2017',
                'outlet': 'GENIUS',
                'subject_matter': 'Playboi Carti "wokeuplikethis*" Official Lyrics & Meaning | Verified',
                'special_notes': 'Carti talks about how producer PierreBourne made the track in the back of an Uber and Carti ended up hearing it through Instagram',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=ZVA_TdxFEy4',
            },
            {
                'era': 'Playboi Carti',
                'date': 'May 3, 2017',
                'outlet': 'HOT 97',
                'subject_matter': "Playboi Carti Talks Being A Mystery,Respecting 'Older' Artists & Shares His Influences",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/MOURO7uQ0eE?si=yLuykLQ_Y7X8lqoG',
            },
            {
                'era': 'Playboi Carti',
                'date': 'May 16, 2017',
                'outlet': 'Mass Appeal',
                'subject_matter': 'Shop Talk: Playboi Carti',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/jPkLlmKXEE0?si=VT-9k664Q7USUch5',
            },
            {
                'era': 'Playboi Carti',
                'date': 'May 17, 2017',
                'outlet': 'SSENSE',
                'subject_matter': 'Playboi Carti Discusses Social Media and the Afterlife',
                'special_notes': '"I love butterflies. I have a butterfly chain, butterfly ring, butterfly tat. I feel like that\'s me, watching myself blossom, getting over my insecurities, getting confident, and just rising. Just spreading my wings and flying."',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.ssense.com/en-us/editorial/music/rap-game-reincarnation\nhttps://hypebeast.com/2018/5/playboi-carti-ssense-2017-interview',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 13, 2017',
                'outlet': '88rising',
                'subject_matter': 'Rappers React to Higher Brothers | Migos, Lil Yachty, Playboi Carti, KYLE, & more',
                'special_notes': '',
                'interview_type': 'Reaction',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=LDrLlIj0qes',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 13, 2017',
                'outlet': '88rising',
                'subject_matter': 'Raw footage of Carti reacting to Higher Brothers',
                'special_notes': '',
                'interview_type': 'Reaction',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/lWKicHyDGw4?si=e7cz5Q_AnQgRIZ21',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 21, 2017',
                'outlet': 'XXL',
                'subject_matter': 'Playboi Carti Profile Interview - 2017 XXL Freshman',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://youtu.be/vqHY3r2Mr6I?si=Nj5DWOJzlJjx1PUc',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 2017',
                'outlet': 'WMIB 103.5 The Beat',
                'subject_matter': 'Interview with Playboi Carti & Swoosh God',
                'special_notes': 'Leaked December 4th 2024, video quality is terrible, also features Swoosh God.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=nyKwxwaBeHQ',
            },
            {
                'era': 'Playboi Carti',
                'date': 'June 27, 2017',
                'outlet': 'REAL 92.3 LA',
                'subject_matter': 'Playboi Carti in The BET Awards Radio Room w/ Dj A-Oh',
                'special_notes': "This is the most I've seen Carti talk",
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=nDnCIyYjbuU&t=178s',
            },
            {
                'era': 'Playboi Carti',
                'date': 'August 12, 2017',
                'outlet': 'THE FAM',
                'subject_matter': 'Playboi Carti Smokes A Blunt During Live Interview With The Fam',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=4zuJLNE77o8&t=52s',
            },
            {
                'era': 'Playboi Carti',
                'date': 'September 26, 2017',
                'outlet': 'HIGHSNOBIETY',
                'subject_matter': "Here's What Happened When Gucci Mane Met Playboi Carti",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=YvZjbB_hwGE',
            },
            {
                'era': 'Playboi Carti',
                'date': '2017',
                'outlet': 'BRICK Magazine',
                'subject_matter': 'Carti opens up about high expectations',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': False,
                'archived_link': '',
                'source_links': '',
            },
            {
                'era': 'Playboi Carti',
                'date': '2017',
                'outlet': 'CLOTHESMINDED',
                'subject_matter': 'Playboi Carti Interview - Clothesminded',
                'special_notes': 'Original is not available',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=wIVd7T45uJU&t=1s',
            },
            {
                'era': 'Playboi Carti',
                'date': '2017',
                'outlet': 'Nike',
                'subject_matter': 'Playboi Carti Interview - Nike DiscoverYourAir',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=QXloYzJ9bR4',
            },
            {
                'era': 'Playboi Carti',
                'date': '2017',
                'outlet': 'Nike',
                'subject_matter': 'Playboi Carti Nike Ad',
                'special_notes': '',
                'interview_type': 'Promo',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=fml4MjmDZWA',
            },
            
            # Die Lit Era
            {
                'era': 'Die Lit',
                'date': 'May 1, 2018',
                'outlet': 'Office Magazine',
                'subject_matter': 'In person',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://officemagazine.net/playboi-carti-person',
            },
            {
                'era': 'Die Lit',
                'date': 'June 4, 2018',
                'outlet': 'Dazed',
                'subject_matter': "Discusses Cati's punk attire",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.dazeddigital.com/music/article/40231/1/playboi-carti-die-lit-modern-punk-icon-interview',
            },
            {
                'era': 'Die Lit',
                'date': 'July 10, 2018',
                'outlet': 'TimWestwoodTV',
                'subject_matter': 'Playboi Carti on pimp game, Milly Rock, Skepta, XXXTentacion, fashion - Wireless 2018',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=mP4C_6gO-68&t=17s',
            },
            {
                'era': 'Die Lit',
                'date': 'July 27, 2018',
                'outlet': 'Power 106 Los Angeles',
                'subject_matter': "Playboi Carti On Modeling For Virgil Abloh, Relationship w/ Nicki Minaj & Chief Keef's Influence",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=PNMpuBVL_wE&t=89s',
            },
            {
                'era': 'Die Lit',
                'date': 'July 31, 2018',
                'outlet': 'Power 106 Los Angeles',
                'subject_matter': "Playboi Carti talks Unreleased Frank Ocean Collabs, 'Die Lit' + Clubbing with his Pops",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=jhop5HYxD_w&t=97s',
            },
            {
                'era': 'Die Lit',
                'date': 'July 31, 2018',
                'outlet': 'REAL 92.3 LA',
                'subject_matter': 'Playboi Carti Shres About A$AP Rocky & His Album With Lil Uzi',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=OFJILoRc6hU&t=4s',
            },
            {
                'era': 'Die Lit',
                'date': 'August 1, 2018',
                'outlet': 'REVOLT',
                'subject_matter': 'Playboi Carti ranks soundalike rappers, quitting lean, and Bam Margera | On Clout 9',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=Tn6NqfJpp_k&t=7s',
            },
            {
                'era': 'Die Lit',
                'date': 'August 4, 2018',
                'outlet': 'BigBoyTV',
                'subject_matter': "Playboi Carti on 'Die Lit', XXL Freshman List, Meeting A$AP Rocky & More!",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/results?search_query=(BigBoyTV)+Playboi+Carti+on%27Die+Lit%27%2C+XXL+Freshman+List%2C+Meeting+A%24AP+Rocky+%26+More!',
            },
            {
                'era': 'Die Lit',
                'date': '2018',
                'outlet': 'Unknown',
                'subject_matter': 'Fredo Santana & Playboi Carti',
                'special_notes': 'R.I.P. Fredo',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=kYaipB4YOwY',
            },
            {
                'era': 'Die Lit',
                'date': '2018',
                'outlet': 'Interview with Ted Stryker',
                'subject_matter': 'Playboi Carti Interview with Ted Stryker',
                'special_notes': 'Carti talks about how he wants his name to hold weight and to be seen more than just a rapper in future. Missing perfomances in the interview due to copyright.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=ebutZh2kX8E',
            },
            
            # Whole Lotta Red [V1] Era
            {
                'era': 'Whole Lotta Red [V1]',
                'date': 'August 14, 2018',
                'outlet': 'HOT 97',
                'subject_matter': "Playboi Carti Reveals He Had A 'Good Week' w/ Blac Chyna & Talks Face Tattoos & Lean",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=6ruDaG76xtU&t=219s',
            },
            
            # Whole Lotta Red [V2] Era
            {
                'era': 'Whole Lotta Red [V2]',
                'date': 'June 12, 2019',
                'outlet': 'FADER Magazine',
                'subject_matter': '',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.thefader.com/2019/06/12/playboi-carti-cover-story',
            },
            {
                'era': 'Whole Lotta Red [V2]',
                'date': 'Summer 2019',
                'outlet': '032c',
                'subject_matter': '',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://032c.com/magazine/the-playboi-mansion',
            },
            {
                'era': 'Whole Lotta Red [V2]',
                'date': 'January 14, 2020',
                'outlet': 'Culture Kings',
                'subject_matter': '',
                'special_notes': 'Carti talks about his second studio album Whole Lotta Red and how he\'s ready to drop (he proceeded to drop WLR on the last Friday of the year)',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': 'https://krakenfiles.com/view/RqfDntHM6m/file.html',
                'source_links': 'Original got deleted :/',
            },
            
            # Whole Lotta Red [V3] Era
            {
                'era': 'Whole Lotta Red [V3]',
                'date': 'November 23, 2020',
                'outlet': 'GQ Magazine',
                'subject_matter': 'How Playboi Carti Emerged from the Atlanta Underground',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.gq.com/story/playboi-carti-men-of-the-year-profile',
            },
            
            # Whole Lotta Red [V4] Era
            {
                'era': 'Whole Lotta Red [V4]',
                'date': 'March 9, 2021',
                'outlet': 'Inked Magazine',
                'subject_matter': '',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://inkedmag.com/original-news/playboicarti',
            },
            {
                'era': 'Whole Lotta Red [V4]',
                'date': 'March 10, 2021',
                'outlet': 'HIGHSNOBIETY',
                'subject_matter': 'Matthew Williams & Playboi Carti Interview',
                'special_notes': 'Carti talks about his relationship with Matthew Williams',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.highsnobiety.com/p/matthew-m-williams-playboi-carti-interview/',
            },
            
            # Narcissist Era
            {
                'era': 'Narcissist',
                'date': 'May 7, 2021',
                'outlet': 'CRACK Magazine',
                'subject_matter': '',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://crackmagazine.net/article/profiles/playboi-carti-interview/',
            },
            {
                'era': 'Narcissist',
                'date': 'September 12, 2021',
                'outlet': 'Sedition Magazine',
                'subject_matter': 'Rick Owens asks Carti some questions',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.seditionmagazine.com/shop/orwrw4ykwazg3w587j4xobxde1ign2',
            },
            
            # MUSIC Era
            {
                'era': 'MUSIC',
                'date': 'April 12, 2022',
                'outlet': 'XXL',
                'subject_matter': 'Carti announces that his next album is called MUSIC',
                'special_notes': 'First ever mention of MUSIC',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.xxlmag.com/playboi-carti-xxl-magazine-spring-2022-issue-cover/',
            },
            
            # I AM MUSIC [V1] Era
            {
                'era': 'I AM MUSIC [V1]',
                'date': 'July 22, 2023',
                'outlet': 'Chris Too Smoove',
                'subject_matter': 'How much is your outfit worth? w/playboicarti',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.instagram.com/p/CvAHj5ztkMf/',
            },
            {
                'era': 'I AM MUSIC [V1]',
                'date': 'November 3, 2023',
                'outlet': 'Numero Berlin Magazine',
                'subject_matter': 'Carti talks about how his next album MUSIC is his best work yet',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.numeroberlin.de/2023/11/numero-berlin-zukunft-x-playboi-carti/',
            },
            {
                'era': 'I AM MUSIC [V1]',
                'date': 'February 5, 2024',
                'outlet': 'Adin Ross Kick Stream',
                'subject_matter': '😐',
                'special_notes': 'This goofball arrived 2 hours late, stood in the dark the whole time with the mask on and said total of 6 words, took 2 million dollars of cash and then dipped.',
                'interview_type': 'Stream',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=atr4logxn3E',
            },
            
            # I AM MUSIC [V2] Era
            {
                'era': 'I AM MUSIC [V2]',
                'date': 'September 3, 2024',
                'outlet': 'Billboard',
                'subject_matter': "Behind the scenes of Carti's show alongside with exclusive Destroy Lonely and Carti's manager Marie Lars interviews",
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.youtube.com/watch?v=49T5Y3173Mc',
            },
            {
                'era': 'I AM MUSIC [V2]',
                'date': 'September 3, 2024',
                'outlet': 'Billboard Magazine',
                'subject_matter': '',
                'special_notes': '',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://www.billboard.com/music/rb-hip-hop/playboi-carti-cover-story-interview-1235764638/',
            },
            {
                'era': 'I AM MUSIC [V2]',
                'date': 'March 13, 2025',
                'outlet': 'i-D Magazine',
                'subject_matter': 'Carti asks FKA Twigs some questions for i-D Magazine',
                'special_notes': 'Not really a Carti interview but more so Carti is interviewing someone else.',
                'interview_type': 'Interview',
                'available': True,
                'archived_link': '',
                'source_links': 'https://i-d.co/article/fka-twigs-cover-story/',
            },
        ]
        
        # Clear existing data if needed
        if Interview.objects.exists():
            self.stdout.write(self.style.WARNING('Clearing existing interview data...'))
            Interview.objects.all().delete()
        
        # Import the data
        interviews_created = 0
        for data in interview_data:
            interview = Interview.objects.create(
                era=data['era'],
                date=data['date'],
                outlet=data['outlet'],
                subject_matter=data['subject_matter'],
                special_notes=data['special_notes'],
                interview_type=data['interview_type'],
                available=data['available'],
                archived_link=data['archived_link'],
                source_links=data['source_links'],
            )
            interviews_created += 1
            
        self.stdout.write(self.style.SUCCESS(f'Successfully imported {interviews_created} interviews'))