from django.core.management.base import BaseCommand
from catalog.models import SheetTab, SongCategory, CartiCatalog, SongMetadata

class Command(BaseCommand):
    help = 'Removes tabs after Stems and adds stems data from Google Sheets'

    def add_arguments(self, parser):
        parser.add_argument(
            '--dry-run',
            action='store_true',
            dest='dry_run',
            help='Show what would be deleted without actually deleting',
        )

    def handle(self, *args, **options):
        dry_run = options['dry_run']
        
        # Get all tabs ordered as they appear in the dropdown
        tab_order_map = {
            'Released': 1,
            'Unreleased': 2,
            '🏆 Grails': 3,
            '🥇 Wanted': 4,
            '⭐ Best Of': 5,
            '✨ Special': 6,
            '🤖 AI Tracks': 7,
            '🗑️ Worst Of': 8,
            'OG Files': 9,
            'Recent': 10,
            'Stems': 11,
        }
        
        # Get all tabs
        all_tabs = SheetTab.objects.all()
        
        # Tabs to remove (anything after Stems and not in our order map)
        tabs_to_remove = []
        
        # Find tabs to remove
        for tab in all_tabs:
            if tab.name not in tab_order_map or tab_order_map.get(tab.name, 0) > tab_order_map.get('Stems', 0):
                if tab.name != 'Stems':  # Make sure we don't remove Stems itself
                    tabs_to_remove.append(tab)
        
        if not tabs_to_remove and not dry_run:
            self.stdout.write(self.style.WARNING('No tabs to remove'))
        else:
            self.stdout.write(f'Found {len(tabs_to_remove)} tabs to remove:')
            for tab in tabs_to_remove:
                self.stdout.write(f'  - {tab.name} (ID: {tab.id})')
                
                # Count songs in this tab
                song_categories = SongCategory.objects.filter(sheet_tab=tab)
                if song_categories.exists():
                    self.stdout.write(f'    Found {song_categories.count()} songs in this tab')
                    
                    if not dry_run:
                        self.stdout.write(f'    Removing song associations for {tab.name}...')
                        song_categories.delete()
                
                # Delete the tab itself
                if not dry_run:
                    self.stdout.write(f'    Deleting tab: {tab.name}')
                    tab.delete()
        
        # Now add stems data from Google Sheets
        if not dry_run:
            # Get or create Stems tab
            stems_tab, created = SheetTab.objects.get_or_create(name='Stems')
            
            if created:
                self.stdout.write(self.style.SUCCESS(f'Created new Stems tab with ID {stems_tab.id}'))
            else:
                self.stdout.write(f'Using existing Stems tab with ID {stems_tab.id}')
                
            # Define stems data
            stems_data = [
                {
                    'era': '$ir Cartier',
                    'name': '36 Villainz [Instrumental] (prod. Cold Hart)',
                    'notes': 'Instrumental for "36 Villainz".',
                    'leak_date': 'Sep 6, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/9X4u4oXMkR/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Blue Crystal$ [Instrumental] (prod. Tom Voduz)',
                    'notes': 'Instrumental for "Blue Crystal$".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/r7qSc3XtNQ/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Carolina Blue Freestyle [Instrumental] (prod. Cookin Soul)',
                    'notes': 'Instrumental for "Carolina Blue Freestyle".',
                    'leak_date': 'Sep 6, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/pufL0sjqJ9/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Living Reckle$$ [Instrumental] (prod. Ski Beatz)',
                    'notes': 'Instrumental for "Living Reckle$$"',
                    'leak_date': '2011',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/4zVdwRCwrG/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Outchea [Instrumental] (prod. Tay Lewis)',
                    'notes': 'Instrumental for "Outchea".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/LzDOJKs310/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'So Cold [Instrumental] (prod. J Endo Productions)',
                    'notes': 'Instrumental for "So Cold".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/u6MBAL7YHU/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': '$teeze [Instrumental] (prod. TDeeZy)',
                    'notes': 'Instrumental for "$teeze".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/30r9UuSVhe/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Terror Shit [Instrumental] (prod. E.beats, 1panicattack & MelroseZee)',
                    'notes': 'Instrumental for "Terror Shit".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/B73Kfrugl1/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Van Go [Instrumental] (prod. Cold Hart)',
                    'notes': 'Instrumental for "Van Go".',
                    'leak_date': 'May 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/XDvLBv9vVQ/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Faster [Instrumental] (prod. Naughty Gawd)',
                    'notes': 'Instrumental for "Faster".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/KbeerxzGvH/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'This Cash [Instrumental] (prod. MelroseZee & DbeatzBitch)',
                    'notes': 'Instrumental for "This Cash".',
                    'leak_date': '2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/78f5ee362be2377db405aef981edc82d',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Dope [Instrumental] (prod. Jones Beatz)',
                    'notes': 'The original instrumental for Dope was a type beat prod. by Jones Beatz and uploaded Dec 7, 2012. The song was only heard at the end of the H2O song so only a short bit was heard as it was a teaser for the Dope.',
                    'leak_date': 'Dec 7, 2012',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/87340eada5294e30f65aab6c10ce0e7a\nhttps://www.youtube.com/watch?app=desktop&v=CzGwRe-EJFA',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'YUNGXANHOE [Instrumental] (prod. Sqvxlls)',
                    'notes': 'The original instrumental for YUNGXANHOE was a type beat prod. by Sqvxlls and uploaded Feb 6, 2013. The beat is cut short on Carti\'s track and therefore the full beat is much longer.',
                    'leak_date': 'Feb 6, 2013',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://www.youtube.com/watch?v=Qz1ogaZTBJg',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'For My Set [Sample] (prod. Indolympus)',
                    'notes': 'Samples "Come Morning" by Rocco Ventrella.',
                    'leak_date': '',
                    'type': 'Sample',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/LfcW3eouoT/file.html',
                },
                {
                    'era': '$ir Cartier',
                    'name': 'Paper Cha$e [Sample] (prod. SonoSoloSoul)',
                    'notes': 'Samples "The 6th Sense" by Common.',
                    'leak_date': '',
                    'type': 'Sample',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/doisBC1Ak6/file.html',
                },
                {
                    'era': 'Awful Records',
                    'name': 'Forgiato [Vocal Stems]',
                    'notes': 'Vocal stems for the unreleased song "Forgiato" leaked in 2019 alongside the song.',
                    'leak_date': '',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/f265a2b8acc120a6e466a86c8334c045',
                },
                {
                    'era': 'Awful Records',
                    'name': 'VVS Diamonds [Sample] (prod. Zach Diamonds)',
                    'notes': 'Sample used in VVS Diamonds',
                    'leak_date': '',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://blumarten.bandcamp.com/album/blu-mar-ten-jungle-jungle-1989-to-1999-samplepack',
                },
                {
                    'era': 'Chucky Era',
                    'name': 'Talk (ICYTWAT Remix) [Instrumental] (prod. ICYTWAT)',
                    'notes': 'OG Filename: t icytwat\nOfficial instrumental released by ICYTWAT.',
                    'leak_date': 'Sep 12, 2017',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/2854826af52931a95404b79c101fd0d4',
                },
                {
                    'era': 'Chucky Era',
                    'name': 'Splur Gang [Sample] (prod. Ant Spittah)',
                    'notes': 'Samples "Laurie\'s Theme" by John Carpenter.',
                    'leak_date': '',
                    'type': 'Sample',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/b2ca801222cff8de5e3eb06e3636482b',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': '??? [Instrumental] (prod. lumbyst & Art Dealer)',
                    'notes': 'Instrumental for a beat that Carti likely recorded on (Not 100% Sure).',
                    'leak_date': 'Feb 20, 2025',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://music.froste.lol/song/b969ec91f992f3d83498ea809973593d/play',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': '2.6 Boy [Instrumental] (prod. Richie Souf)',
                    'notes': 'Bitch Boy instrumental posted by richie souf via his richie grails zip.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Zn9F324uev/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Asthma [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Instrumental for Goku/Asthma.',
                    'leak_date': 'Sep 5, 2019',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/9fe9b4ca3fc72c48609ebc173fadad61',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'A$AP Rocky - Buck Shots [Instrumental] (prod. Kelvin Krash)',
                    'notes': 'Official instrumental posted by the producer on his Instagram. (Now archived) Its really low bit rate.',
                    'leak_date': '2018',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://music.froste.lol/song/e9307cf3dbb0f11bff0ded73d4586f7d/play',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Cancún [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Instrumental for Cancún.',
                    'leak_date': 'Nov 7, 2019',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/5c65fc02d2b9d75ce9c9c28c69c32f8f',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Athena [Session] (prod. Maaly Raw)',
                    'notes': 'Full recording session for the song "Athena". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Mar 15, 2021',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://drive.google.com/file/d/1pU4dDC3qALvMJdsEhLS3D-X6vyML6Hik/view',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Back Up [Sample Loop] (prod. CuBeatz)',
                    'notes': 'The original melody used to create "Back Up".',
                    'leak_date': 'Jul 4, 2021',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/966499cdff5d482bb9f4f498633e68ee',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Buffy The Body [Instrumental] (prod. Roark Bailey)',
                    'notes': 'Instrumental for Buffy The Body',
                    'leak_date': 'Oct 18, 2022',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/829c7119c3af55713d61b433d7500463',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Butterfly Doors [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'OG Filename: littletree10 140\nAlternate instrumental for "Butterfly Doors".',
                    'leak_date': '2022',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/nMBFK7kPTr/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Cranked [Instrumental] (prod. Brandon Finessin & Outtatown)',
                    'notes': 'OG Filename: brandonfinessin x outtatown - cranked - 138bpm\nInstrumental for a beat that Carti likely recorded on in 2019 (Not 100% Sure).',
                    'leak_date': 'Mar 1, 2025',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': '',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Designer Shoes [Instrumental] (prod. Chinatown)',
                    'notes': 'OG Filename: bring a friend\nInstrumental for "Designer Shoes".',
                    'leak_date': '2022',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/19fd8c8fb870f0d0ddd586b0dc4aee85',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Dreams [Session] (prod. London On Da Track)',
                    'notes': 'Full recording session for the song "Dreams". Includes the instrumental as well as every recorded vocal for the song',
                    'leak_date': 'Apr 29, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://buzzheavier.com/0b8r6z6ye28x',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Free PDE [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Instrumental for "Free PDE".',
                    'leak_date': '2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://buzzheavier.com/8y6naiqb1471',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Friends [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Instrumental to the leaked song "Friends". Samples "Agony" by Yung Lean.',
                    'leak_date': 'Nov 30, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/vkJNEFitKY/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'In Line [Instrumental] (prod. Metro Boomin)',
                    'notes': 'Instrumental for "In Line".',
                    'leak_date': 'Mar 23, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://www.youtube.com/watch?v=MhFlQUjUUpo&ab_channel=bro',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'N3on [Acapella]',
                    'notes': 'Acapella snippet leaked on 1/17/24 along with Shoota session & @ MEH snippets.',
                    'leak_date': 'Jan 17, 2024',
                    'type': 'Acapella',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/553d61cff22a05f3a75da898d5490952',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Nine Nine [Sample Loop] (prod. beatsbymango)',
                    'notes': 'The original melody used to create "Nine Nine".',
                    'leak_date': 'Dec 3, 2017',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/e5c6b390d9a676e8ccdd376ad0eda87f',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Not Real [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Instrumental for Not Real',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/4f71b02e7fb8d32158ab8dda355b4187',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Not Real [Session]',
                    'notes': 'Headphone bleed with alt vocals heard in Not Real / molly.jpeg. Unknown which version.',
                    'leak_date': '',
                    'type': 'Session',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/cb7923d077f4e2b604d6843f6f638626',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Pissy Pamper [Session]',
                    'notes': 'Snippet of an alternate take heard in headphone bleed.',
                    'leak_date': '',
                    'type': 'Session',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/ec0990a585e56cefd44ac8a11f0f22c0',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Pissy Pamper [Sample Loop]',
                    'notes': 'Samples "Tasogare" by Mai Yamane',
                    'leak_date': '1980',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/aa9860dee307e9a4ac5801e6c8041a53',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Whole Lotta Red [Instrumental] (prod. Maaly Raw)',
                    'notes': 'Instrumental to the unreleased song "Whole Lotta Red". Features alternate production.',
                    'leak_date': '2020',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/eaa1a5bfa1f6bd114e2812fd6d1e0501',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Ye - Bipolar [V2] [Stems] (prod. Wheezy)',
                    'notes': 'Stems for a 2018 version of Bipolar (Go2DaMoon).',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/91662a8af07043274172d36848bedcbd',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Young Jordan - Raf [Session] (feat. Playboi Carti) (prod. Nebu Kiniza)',
                    'notes': 'Unleaked session for "Raf" by Young Jordan featuring Carti.',
                    'leak_date': '',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'Low Quality',
                    'links': 'LINK NEEDED',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Tyler, The Creator - EARFQUAKE [Instrumental] (feat. Playboi Carti) (prod. Tyler, The Creator)',
                    'notes': 'Instrumental for EARFQUAKE.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/54ecefd27b5dd2a2d0310faefaf15dc0',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Tryna Get Down [Instrumental] (prod. Richie Souf)',
                    'notes': 'TGD instrumental posted by richie souf via his richie grails zip.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Bjv5ELOzbw/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V1]',
                    'name': 'Too [Instrumental] (prod. Richie Souf)',
                    'notes': 'Thongs Too instrumental posted by richie souf via his richie grails zip.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/WrA8mxyelS/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': '@ MEH [Acapella]',
                    'notes': 'Full leaked on August 28th along with the lossless instrumental',
                    'leak_date': 'Aug 28, 2024',
                    'type': 'Acapella',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/1e76d88af01d996bb30a5778e56265e7',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': '@ MEH [Instrumental] (prod. jetsonmade, Neeko Baby & Deskhop)',
                    'notes': 'Instrumental to the released song "@ MEH".',
                    'leak_date': 'Aug 28, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/5963ed1c43c10cb58af0ba9f119793ed',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Money & Drugs [Instrumental] (prod. jetsonmade)',
                    'notes': 'Instrumental to the leaked song "Money & Drugs".',
                    'leak_date': '2020',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/b89bfc032bbcaabe86e93f7905df6656',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Trenches [Instrumental] (prod. Zaytoven)',
                    'notes': 'Instrumental to the unleaked song "Trenches". Originally used for "Make Tha Trap Say Aye" by Oj Da Juice Man',
                    'leak_date': '2009',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/bdf63e1e52b441a7a78f4bad49f57c4b',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Headshot [Instrumental] (prod. Richie Souf)',
                    'notes': 'Headshots instrumental posted by richie souf via his richie grails zip.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/XETLzHZhnA/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Hellraiser [Instrumental] (prod. Samba Beatz & Sgull)',
                    'notes': 'Hellraiser instrumental posted by the producers on youtube.',
                    'leak_date': 'Aug 17, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/iLvEvBWO9p/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'My Cup [Instrumental] (prod. Richie Souf)',
                    'notes': 'My Cup instrumental posted by richie souf via his richie grails zip. Unlike Carti\'s version, the intro does not restart.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/8EhyiDByuC/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Not For Me [Instrumental] (prod. Richie Souf)',
                    'notes': 'Not For Me instrumental posted by richie souf via his richie grails zip.',
                    'leak_date': 'Aug 31, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/wv2N8jWSw6/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Pushed in a Room Filled Wit Love [Instrumental] (prod. Richie Souf)',
                    'notes': 'Superstar instrumental leaked as a bonus to Flexxin gb.',
                    'leak_date': 'Oct 30, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/R3RdobUGUu/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'U Kan Do It Too [Instrumental] (prod. Richie Souf)',
                    'notes': 'Instrumental for U Kan Do It Too.',
                    'leak_date': '2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/7c6e022955236d805067432b1c7caaa0',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Capo DTE - Get It Up [Instrumental] (prod. Samba Beatz)',
                    'notes': 'Instrumental for Get It Up, has some mixing diffrences tho.',
                    'leak_date': 'Mar 26, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://youtu.be/8sSgh2rtlkk',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Drake - Pain 1993 [Instrumental] (feat. Playboi Carti) (prod. Pi\'erre Bourne)',
                    'notes': 'OG Filename: melee 154.5bpm\nInstrumental to the released song "Pain 1993" by Drake featuring Carti. Filename shows the beat was named "Melee".',
                    'leak_date': '2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/7ebfea0da253594872396ddcc53c997b',
                },
                {
                    'era': 'Whole Lotta Red [V2]',
                    'name': 'Yung Bans - High As Us [Sessions] (feat. Playboi Carti) (prod. Bugz Ronin)',
                    'notes': 'Leaked by monix as a bonus for the "U Kan Do It Too" groupbuy.',
                    'leak_date': 'Mar 25, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/uj1GDvvJPe/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V3]',
                    'name': 'Diamonds [Instrumental] (prod. Pi\'erre Bourne)',
                    'notes': 'Previewed on Chris\' twitter.',
                    'leak_date': 'Apr 1, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/0edd1ebba9bf344dce725ea45c50b4b3',
                },
                {
                    'era': 'Whole Lotta Red [V3]',
                    'name': 'K Suave - Perky97* [Instrumental] (feat. Playboi Carti) (prod. PinkGrillz)',
                    'notes': 'Original type beat that K Suave & Carti would use for the track "Perky97".',
                    'leak_date': 'Jul 27, 2020',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://www.youtube.com/watch?v=GZabc8iMGxw',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Can\'t Fake It [Session]',
                    'notes': 'Recording session for the song "Can\'t Fake It". Missing the instrumental and some vocal takes.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Partial',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/rYdyufGms4/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Dick Pleaser [Instrumental] (prod. Lil Jon)',
                    'notes': 'Instrumental to the leaked song "Dick Pleaser". Originally used for "Dick Pleaser" by Lil Wayne.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/db59cb4702729f58fcb430854d087c04',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Die4Guy [Instrumental] (prod. Art Dealer, Outtatown & star boy)',
                    'notes': 'OG Filename: 2004_suicidal_149BPM_SB_OT_ART.mp3\nInstrumental to the released song "Die4Guy".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/s02lH1VeU7/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Everyday [Instrumental] (prod. DP Beatz)',
                    'notes': 'Instrumental for "Everyday" on 0:13 to 0:48.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/cb0a8e0173b8d1ceba9653d197284f97',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'F33l Lik3 Dyin [Instrumental] (prod. Richie Souf & Roark Bailey)',
                    'notes': 'Instrumental to the released song "F33l Lik3 Dyin".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/c74c75f1fbf97a8b0075ad1109b3a344',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Flex Up [Session] (prod. Southside, ATL Jacob & Pyrex)',
                    'notes': 'Flex up session. Leaked as a bonus to VETEMENTS JEANS groupbuy.',
                    'leak_date': 'Oct 5, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://drive.google.com/file/d/14BXm-rxZp8uUAT7k5a0pfM7rdVcFIOll/view?usp=sharing',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Go2DaMoon [Sample Stem] (prod. Wheezy)',
                    'notes': 'Go2DaMoon sample stem.',
                    'leak_date': 'Sep 18, 2023',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/tp4K39eN7u/file.html\nhttps://krakenfiles.com/view/9wtTJLkEPg/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Go2DaMoon [Session] (feat. Kanye West) (prod. Wheezy)',
                    'notes': 'Unleaked session for "Go2DaMoon".',
                    'leak_date': '',
                    'type': 'Session',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/dbb7cd3b77afe5dcda597c37350a5cad\nhttps://pillowcase.su/f/9a035bb5f722baf037da6e3805c39273\nhttps://pillowcase.su/f/8319d400ff77123ed441e2da054102fb',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Going Outta Style [Session] (Medusa, Rager)',
                    'notes': 'Full recording session for the song "Going Outta Style". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/7V55foTjs8/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'JumpOutTheHouse [Instrumental] (prod. Richie Souf)',
                    'notes': 'Instrumental to the released song "JumpOutTheHouse". Features slightly alternate production and has a Richie Souf tag.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/33a2ed0fb5c788bfcdb9a26605bc11d1',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Money [Session]',
                    'notes': 'Full recording session for the song "Money". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/X1sRSJiWKH/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Never Seen Shit [Session]',
                    'notes': 'Full recording session for the song "Never Seen Shit". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/5IxpXmh3PS/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'New N3on [Instrumental] (prod. Maaly Raw)',
                    'notes': 'Instrumental to the released song "New N3on".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/ccf17707410891f87511489e462c0a54',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'New Tank [Instrumental] (prod. F1LTHY & Jonah Abraham)',
                    'notes': 'OG Filename: f1l jon tank 151\nInstrumental to "New Tank".',
                    'leak_date': 'Jul 21, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/YfaOrgl846/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'New Tank [Loop] (prod. F1LTHY & Jonah Abraham)',
                    'notes': 'Official synth loop for "New Tank".',
                    'leak_date': '',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/20ec39e4db78edabbee94f95115aab60',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'On That Time [Instrumental] (prod. F1LTHY & Ojivolta)',
                    'notes': 'OG Filename: f1l oji draco 150\nInstrumental to "On That Time".',
                    'leak_date': 'Jul 21, 2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/bdftR4Mi7m/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'ILoveUIHateU [Synth Sample] (prod. Pi\'erre Bourne)',
                    'notes': 'Synth Sample to "ILoveUIHateU"',
                    'leak_date': 'Jul 6, 2021',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/313a86a410d946149cd9d496e0aecc26',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Over [Instrumental] (prod. Art Dealer)',
                    'notes': 'Instrumental to the released song "Over".',
                    'leak_date': 'Dec 21, 2022',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/SLpOzzXa3w/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Popular [Session]',
                    'notes': 'Full recording session for the song "Popular". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/jqbVcUug1B/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Punk Monk [Instrumental] (prod. F1LTHY, Lucian & Lukrative)',
                    'notes': 'Played by F1LTHY on an Instagram livestream.',
                    'leak_date': 'Mar 13, 2021',
                    'type': 'Instrumental',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/q0SRGdGuVV/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Pour Me Up [Session] (prod. DHill)',
                    'notes': 'Full recording session for the song "Pour Me Up". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/enJQoyLAcI/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Ridin\' [Session] (prod. KP Beatz & Fluxury)',
                    'notes': 'Full recording session for the song "Ridin". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/lXpgxdTBJR/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Rockstar Shit [Session]',
                    'notes': 'Full recording session for the song "Rockstar Shit". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Q6kYVLfQ6q/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Slay3r [Instrumental] (prod. Juberlee & Roark Bailey)',
                    'notes': 'Instrumental to the released song "Slay3r".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/MMsIPRsgi2/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Slay3r [Melody] (prod. Juberlee & Roark Bailey)',
                    'notes': 'Melody breakdown of "Slay3r" posted by Juberlee.',
                    'leak_date': 'Apr 27, 2024',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/c1f87c7ed7c32cdc8b7ad62692f084be',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Tall Sprite [Instrumental] (prod. F1LTHY, Lukrative, ssort)',
                    'notes': 'Previewed by F1LTHY on Instagram live and on @alifewelivedallalong\'s story. Used in Tsunami by SJ3 Zeno with Lancey Foux.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Snippet',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Z72ePw2WAi/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Too Many Bags [Session]',
                    'notes': 'Full recording session for the song "Too Many Bags". Includes the instrumental as well as every recorded vocal for the song.',
                    'leak_date': 'Apr 30, 2023',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/tZ2kqC4wad/file.html',
                },
                {
                    'era': 'Whole Lotta Red [V4]',
                    'name': 'Kid Cudi - Solo Dolo Pt. IV [Session] (feat. Playboi Carti)',
                    'notes': 'Password protected .zip file leaked in 2023.\nThe password is "BellyFat69!". Leaked after a succesful gb.',
                    'leak_date': 'Apr 15, 2024',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pixeldrain.com/u/ArLJ3zwp',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Junya [Stems] (feat. Playboi Carti) (prod. Ojivolta, Digital Nas & Roark Bailey)',
                    'notes': 'Four track stems released on the Stem Player.',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/HPh36Jgnms/file.html',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Junya [Stems] (feat. Playboi Carti) (prod. Ojivolta, Digital Nas & Roark Bailey)',
                    'notes': '7/26 stems for Junya',
                    'leak_date': 'Jul 26, 2021',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/84c6df6d4d46f1a280000e678e128936',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Junya pt 2 [Stems] (feat. Playboi Carti & Ty Dolla $ign) (prod. Ojivolta, Digital Nas & Roark Bailey)',
                    'notes': 'Four track stems released on the Stem Player.',
                    'leak_date': 'Jul 26, 2021',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/oxkErd23Au/file.html',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Off The Grid [12.22.20] [Stems] (feat. Playboi Carti) (prod. 30 Roc)',
                    'notes': 'Stems for OG version of Off The Grid.',
                    'leak_date': 'Sep 20, 2021',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/8509ef18a4f2d9618bb5f063f723e334',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Off The Grid [Stems] (feat. Playboi Carti & Fivio Foreign) (prod. 30 Roc, Ojivolta, AyoAA, Sloane & David & Eli)',
                    'notes': 'Four track stems released on the Stem Player.',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/7qt3NaEFYb/file.html',
                },
                {
                    'era': 'Donda',
                    'name': 'Ye - Made It [88-Keys Version) (feat. Playboi Carti) (prod. OjiVolta & 88-Keys)',
                    'notes': 'Stems for 88-Keys version of Made It',
                    'leak_date': 'Oct 22, 2023',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/BKfHj6ZN69/file.html',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Fuck Em (prod. F1LTHY & Starboy)',
                    'notes': 'Instrumental for Fuck Em',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/fYUOirSKBr/file.html',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Slay3r (SNL Version) [V7] (prod. Juberlee & Roark Bailey)',
                    'notes': 'Instrumental and Acappella of Slay3r SNL Take 3 V3',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/a941ba215895c2f514419a865fb1bdee\nhttps://pillowcase.su/f/0ab84c1d54adc531673a4c1155e7ba7a',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Slay3r (SNL Version) [V10] (prod. Juberlee & Roark Bailey)',
                    'notes': 'Instrumental and Acappella of Slay3r SNL Take 4 V3',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/750b5332fb52d848362a897428ded71c\nhttps://pillowcase.su/f/6173b1537bc21c9ca922e48c93f44017',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Made It This Far [Sample] (prod. Digital Nas)',
                    'notes': 'Analog by Prepare My Glider. Was found in a compilation from the sample stem\'s filename, the same compilation sampled in "Wait" by Ye.',
                    'leak_date': '',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/cec714eede2b9bee4a7c87b023b6a792',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Made It This Far [Beat Stems] (prod. Digital Nas)',
                    'notes': 'Instrumental stems to Made It This Far from Digital Nas\'s downloads folder.',
                    'leak_date': 'Dec 20, 2024',
                    'type': 'Beat Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/GHa49NpCzS/file.html',
                },
                {
                    'era': 'Narcissist',
                    'name': 'New Tank (Tour Version) [Stems] (prod. F1LTHY & Jonah Abraham)',
                    'notes': 'Instrumental stems to the Tour version of "New Tank" used on the Narcissist Tour',
                    'leak_date': '',
                    'type': 'Beat Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Dmjp5NfGK1/file.html',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Vetements Jeans [Instrumental] (prod. Maaly Raw)',
                    'notes': 'Instrumental for the unreleased song "Vetements Jeans" previewed by Maaly Raw on a livestream. Leaked sometime shortly before the actual song itself leaked.',
                    'leak_date': '2023',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://music.froste.lol/song/8c3ffcb7368fcd2e115224e0d66ec424/play',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Trippie Redd - Miss The Rage [Instrumental] (prod. Loesoe)',
                    'notes': 'Instrumental to the released song "Miss The Rage".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/7279d0acb55ba42c9cd1e3fec37ac2e4',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Homixide Gang - Ready To Crash [Instrumental] (prod. Artist)',
                    'notes': 'Official instrumental for the leaked song Ready To Crash. The instrumental was actually uploaded to the producers YouTube before the track leaked and was deleted right after.',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/CkHQIg0GIQ/file.html',
                },
                {
                    'era': 'Narcissist',
                    'name': 'Trippie Redd - Miss The Rage [Acapella] (feat. Playboi Carti)',
                    'notes': 'Vocal stem for Carti\'s verse on "Miss The Rage". No Trippie vocals.',
                    'leak_date': '',
                    'type': 'Acapella',
                    'available_length': 'Partial',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/e6dec47b234999acfe6efda2b4bfbbf2',
                },
                {
                    'era': 'MUSIC [V1]',
                    'name': 'Ye - City Of Gods [V8] (with Fivio Foreign & Alicia Keys) (feat. Playboi Carti) (prod. Ye, AyoAA, Ojivolta, Dem Jointz, Non Native, BoogzDaBeast, Hemz, Tommy Rush, Tweek Tune, Lil Mav, Bordeaux & MIKE DEAN)',
                    'notes': 'Stems of City Of Gods. Ripped from the stem player.',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/d6f5f7136557cf0d19c2a4a471f2de98',
                },
                {
                    'era': 'MUSIC [V1]',
                    'name': 'Ye - Mr. Miyagi (feat. Future & Playboi Carti) (prod. AyoAA)',
                    'notes': 'Stems of Mr. Miyagi. Leaked on May 19, 2023.',
                    'leak_date': 'May 19, 2023',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/6010baa79862caa7bc5ca0c83e6d18e3',
                },
                {
                    'era': 'MUSIC [V1]',
                    'name': 'Ye - We Did It Kid (feat. Migos, Rich The Kid & Playboi Carti) (prod. AyoAA)',
                    'notes': 'Stems for WDIK version featuring Migos, Rich The Kid and Carti adlibs. Leaked on April 28, 2023',
                    'leak_date': 'Apr 28, 2023',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/5a08a87fd2dad26eccbef48eea3b7e6e',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': 'The Weeknd & Madonna - Popular [Stems] (with Playboi Carti) (prod. Metro Boomin, MIKE DEAN, The Weeknd, & Tommy Rush)',
                    'notes': '5 track stems to Popular from Fortnite.',
                    'leak_date': '',
                    'type': 'Studio Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/Pg7UbUXLfM/file.html',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': 'The Weeknd & Madonna - Popular [Instrumental] (with Playboi Carti) (prod. Metro Boomin, MIKE DEAN, The Weeknd, & Tommy Rush)',
                    'notes': 'Instrumental to the released song "Popular".',
                    'leak_date': '',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/65c6d698f42a67ffcab1dfa01ce419ab',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': 'The Weeknd & Madonna - Popular [Acapella] (with Playboi Carti) (prod. Metro Boomin, MIKE DEAN, The Weeknd, & Tommy Rush)',
                    'notes': 'Acapella to the released song "Popular".',
                    'leak_date': '',
                    'type': 'Acapella',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/3a0085a4299e1e7647a613ee64793c31',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': 'MEET YO MAKER [Remix] [INSTRUMENTAL]* (prod. Tommy Wright II & X-Rated Al)',
                    'notes': 'The Instrumental for MEET YO MAKER [Remix]. Originally from Meet Yo Maker by Tommy Wright III.',
                    'leak_date': '2006',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://youtu.be/4jr0atQtl14?si=HCqXGyGTFXVlM4HT',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': 'Travis Scott - FE!N [Dolby Atmos Stems] (feat. Playboi Carti & Sheck Wes) (prod. Travis Scott & Jahaan Sweet)',
                    'notes': 'Dolby Atmos stems ripped from Apple Music.',
                    'leak_date': '',
                    'type': '5.1 Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/8d21301546154c5912c3b909da995be1',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': '¥$ - FIELD TRIP [Acapella] (feat. Playboi Carti, Don Toliver & Kodak Black)',
                    'notes': 'Acapella of the Don Toliver hook for Field Trip. This seems to be from one of the first versions when it was Don\'s song.',
                    'leak_date': '',
                    'type': 'Acapella',
                    'available_length': 'Partial',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/b8c6f779fc54de61a099aec140a66688',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': '¥$ - FIELD TRIP [Instrumental] (prod. Wheezy)',
                    'notes': 'Instrumental mix of Don Toliver\'s DISCONNECTED (FIELD TRIP) from 12/2/23.',
                    'leak_date': 'Oct 21, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/fbb085755d817d7733aab1833360a888',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': '¥$ - FIELD TRIP [Ye Session] (prod. Wheezy, Dez Wright)',
                    'notes': 'Ye\'s freestyle vocal takes from the Field Trip session.',
                    'leak_date': 'Oct 21, 2024',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://plwcse.top/f/456956143b8ae500844f13a45c6062ea\nhttps://plwcse.top/f/e8a5df1a07ab7b8eea2c31943992c937',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': '¥$ - FUK SUMN [V5] (feat. Playboi Carti & Quavo) (prod. Digital Nas, Timbaland, SHDØW, Hubi & Shaun Enzo)',
                    'notes': 'Solo Carti acapella for a 10/7/23 version of Fuk Sumn',
                    'leak_date': 'May 20, 2024',
                    'type': 'Acapella',
                    'available_length': 'Partial',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/0d34ab2c3435995d23fb753a98dc197c',
                },
                {
                    'era': 'I AM MUSIC [V1]',
                    'name': '¥$ - MELROSE [Ye Session] (prod. Wheezy)',
                    'notes': 'Ye\'s freestyle vocal take from the Melrose session.',
                    'leak_date': 'Oct 21, 2024',
                    'type': 'Session',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/b941cb43d459fd1f8a476bbe036834bc',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': 'ALL RED [Instrumental] (prod. F1LTHY, Lukrative, Lucian, OjiVolta & Twisco)',
                    'notes': 'Official instrumental to "ALL RED".',
                    'leak_date': 'Sep 19, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/518ab690466a1c5618900447a664acf8',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': 'COCAINE NOSE [Sample]',
                    'notes': 'Only U\' by Ashanti.',
                    'leak_date': '',
                    'type': 'Other',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://www.youtube.com/watch?v=Y4IjiJI_pNU',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': 'REAL MUSIC [Instrumental] (prod. DJ Heroin, Roark, Ojivolta)',
                    'notes': 'Official instrumental for "REAL MUSIC" leaked in an Ojivolta x Opium beat pack.',
                    'leak_date': '2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/783a116a6af0b83651cec34b8d920dc2',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': '¥$ - CARNIVAL [ACAPELLA] (feat. Playboi Carti & Rich The Kid)',
                    'notes': 'Released via the CARNIVAL PACK.',
                    'leak_date': 'Feb 15, 2024',
                    'type': 'Acapella',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/2f0c51055a3153a6849476816e008423',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': '¥$ - CARNIVAL [Instrumental] (prod. TheLabCook, Ojivolta, Digital Nas, Mike Dean & Ye)',
                    'notes': 'Released via the CARNIVAL PACK.',
                    'leak_date': 'Feb 15, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/f953a02dc7cf70e579359498c59abc79',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': '¥$ - FIELD TRIP [Sample] (prod. Dez Wright & Wheezy)',
                    'notes': 'Original sample used in Field Trip from Dez Wright\'s Instagram story.',
                    'leak_date': '',
                    'type': 'Other',
                    'available_length': 'Partial',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/80859cdbd251dded2a6af46ca4359b23',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': 'Camila Cabello - I LUV IT [Instrumental] (feat. Playboi Carti) (prod. El Guincho & Jasper Harris)',
                    'notes': 'Official instrumental of I LUV IT by Camila Cabello.',
                    'leak_date': 'Mar 30, 2024',
                    'type': 'Instrumental',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://pillowcase.su/f/aedfdef1046685693e2f01bb19106a53',
                },
                {
                    'era': 'I AM MUSIC [V2]',
                    'name': 'The Weeknd - Timeless [Dolby Atmos Stems] (feat. Playboi Carti) (prod. Pharrell Williams, Ojivolta, Twisco & Mike Dean)',
                    'notes': 'Dolby Atmos stems of "Timeless".',
                    'leak_date': 'Sep 27, 2024',
                    'type': '5.1 Stems',
                    'available_length': 'Full',
                    'quality': 'High Quality',
                    'links': 'https://krakenfiles.com/view/C859tF9yem/file.html',
                },
            ]
            
            # Create records for each item
            created_count = 0
            for data in stems_data:
                # Check if song already exists to avoid duplicates
                existing = CartiCatalog.objects.filter(
                    name=data['name'], 
                    era=data['era']
                ).first()
                
                if existing:
                    self.stdout.write(f"Song already exists: {data['name']} - Skipping.")
                    continue
                
                # Create the song
                song = CartiCatalog.objects.create(
                    era=data['era'],
                    name=data['name'],
                    notes=data['notes'],
                    leak_date=data['leak_date'],
                    type=data['type'],
                    available_length=data['available_length'],
                    quality=data['quality'],
                    links=data['links'],
                    primary_link=data['links'].split('\n')[0] if data['links'] else None,
                )
                
                # Create the metadata and associate with Stems tab
                SongMetadata.objects.create(
                    song=song,
                    sheet_tab=stems_tab,
                    subsection=None,
                )
                
                created_count += 1
                
            self.stdout.write(self.style.SUCCESS(f'Added {created_count} new items to the Stems tab'))
            
        if dry_run:
            self.stdout.write(self.style.WARNING('\nDRY RUN: No changes were made'))
        else:
            self.stdout.write(self.style.SUCCESS('\nOperation completed successfully!'))